language: ruby

node_js:
  - 10.15.2

rvm:
  - 2.6.2

services:
  - redis-server

cache:
  bundler: true
  directories:
    - ~/.npm
    - node_modules

install:
  - bundle install && npm install

script:
  - npm run ci
